name: Caliper Benchmarks
version: "2.0.0"

caliper:
  blockchain: fabric

info:
  Version: 2.5.9
  Size: 5 Orgs with 5 Peers
  Orderer: Raft
  Distribution: Single Host
  StateDB: LevelDB

channels:
  # channelName of mychannel matches the name of the channel created by test network
  - channelName: mychannel
    # the chaincodeIDs of all the fabric chaincodes in caliper-benchmarks
    contracts:
    - id: drug

organizations:
  - mspid: Org1MSP
    # Identities come from cryptogen created material for test-network
    peers:
      - peer0.org1.example.com
    identities:
      certificates:
      - name: 'manufacturer'
        clientPrivateKey:
          path: '../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
    connectionProfile:
      path: '../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true
  - mspid: Org2MSP
    peers:
      - peer0.org2.example.com
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
        - name: 'transporter'
          clientPrivateKey:
            path: '../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem'
    connectionProfile:
      path: '../test-network/organizations/peerOrganizations/org2.example.com/connection-org2.yaml'
      discover: true
  - mspid: Org3MSP
    peers:
      - peer0.org3.example.com
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
        - name: 'distributor'
          clientPrivateKey:
            path: '../test-network/organizations/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '../test-network/organizations/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/User1@org3.example.com-cert.pem'
    connectionProfile:
      path: '../test-network/organizations/peerOrganizations/org3.example.com/connection-org3.yaml'
      discover: true
  - mspid: Org4MSP
    peers:
      - peer0.org4.example.com
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
        - name: 'pharmacy'
          clientPrivateKey:
            path: '../test-network/organizations/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '../test-network/organizations/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/signcerts/User1@org4.example.com-cert.pem'
    connectionProfile:
      path: '../test-network/organizations/peerOrganizations/org4.example.com/connection-org4.yaml'
      discover: true
